version: '3.7'

services:
  gql-engine:
    image: hasura/graphql-engine:v1.0.0.cli-migrations
    volumes:
      - ./server/migrations:/hasura-migrations
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - sermonbeacon-network
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/sermonbeacon
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_ADMIN_SECRET: secret
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS512", "key": "-----BEGIN CERTIFICATE-----\nMIIC+TCCAeGgAwIBAgIJNt3r4W3ByxitMA0GCSqGSIb3DQEBCwUAMBoxGDAWBgNV\nBAMTD2hlbHBxLmF1dGgwLmNvbTAeFw0xOTA4MjkwMTIyMzlaFw0zMzA1MDcwMTIy\nMzlaMBoxGDAWBgNVBAMTD2hlbHBxLmF1dGgwLmNvbTCCASIwDQYJKoZIhvcNAQEB\nBQADggEPADCCAQoCggEBALQD/e2jkOlFrQu9svxaaP6cPPlURPWW9CbgJltlovIC\nA7X3NiQaVoscOdkmrEqsbJ7tSsUJnCHTmjxE0ZFQBwcfk9u+MCNt9Vw0jQrrFWcT\nvRlcOPyggJVpOf++wwSC7Tl/OucDPZrszktP48yNpwytojXzc66SRQmp8udilbiX\nsbvJntakUEZoT0cIuKj3RTCTlrwxbaSbTq9oh93RBvcZpy18v8ypG7ptN8YnwB3t\n4yg60HIrhcLRq0nYezWaevrVOACugbg3exN3wcEnTmI+g8+pHMT5WT/yfVgtJn4K\nCHflu/zUB4M0nZX9QHETpwFjNgIOOTDFU7Evhdu/0e8CAwEAAaNCMEAwDwYDVR0T\nAQH/BAUwAwEB/zAdBgNVHQ4EFgQUwm0JfcIZWduf/kFSr1nqpuKDHEEwDgYDVR0P\nAQH/BAQDAgKEMA0GCSqGSIb3DQEBCwUAA4IBAQAtc3G06OpLikWTECTgjgaHZbo/\nIifedM5grjxjaylWdmb9CmSEsIK63/ttF0Nqbt56LHsWiO47/kKwGghfvV4utegw\n2y8FRaIKww5EA/Iqi1VteEqk5Lhnq9v6SSIb3tx0asikMmQDC2N/vdh9BmrXYIZi\nCmHYZG378Bge29gbBPCgRhC9+UDjFJZTg0jF7/n62lIZJ5bUNZD5MllZjzLpihMS\nMiqpSEMRn3mSt+UZNiucyGpBU2WXvSiVFQu34vOT8DWTe+7qIl9tIcTP9HFk4s9+\nBHKKI8msUbyOu3ge1qtV5oTCjgJVFWfjA+3pgajVCpWoWONWeFvHI+PjhdhN\n-----END CERTIFICATE-----\n"}'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log

  postgres:
    image: postgres:alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: sermonbeacon
      POSTGRES_USER: postgres
    networks:
      - sermonbeacon-network
    ports:
      - 5432:5432

networks:
  sermonbeacon-network:
    driver: bridge

volumes:
  db_data:
