name: Deploy Master Apps

on:
  push:
    branches:
      - master

jobs:
  build-admin:
    runs-on: ubuntu-latest
    name: Deploying Admin to Surge
    steps:
      - uses: actions/checkout@v1
      - name: Install surge
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm install -g surge
      - run: cd ./client && npm install
      - run: cd ./client && npm run build:admin
      - run: surge ./client/dist/apps/admin-portal/ https://sb-admin-master.surge.sh --token ${{ secrets.SURGE_TOKEN }}
