name: Deploy Staging Websites

on:
  pull_request:
    branches:
      - master

jobs:
  build-admin:
    runs-on: ubuntu-latest
    name: Deploying Admin to Surge
    steps:
      - uses: actions/checkout@v1
      - name: Install surge
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm install -g surge
      - run: cd ./client && npm install
      - run: cd ./client && npm run build:admin
      - run: surge ./client/dist/apps/admin-portal/ https://sb-admin-${{ github.actor }}.surge.sh --token ${{ secrets.SURGE_TOKEN }}

  build-user:
    runs-on: ubuntu-latest
    name: Deploying User to surge
    steps:
      - uses: actions/checkout@v1
      - name: Install surge
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm install -g surge
      - run: cd ./client && npm install
      - run: cd ./client && npm run build:user
      - run: surge ./client/dist/apps/user-portal/ https://sb-user-${{ github.actor }}.surge.sh --token ${{ secrets.SURGE_TOKEN }}
